import { randomBytes } from 'node:crypto';
import type { ResultSetHeader, RowDataPacket } from 'mysql2/promise';
import { decryptLegacySecret, encryptLegacySecret, tokenHash } from '../../platform/legacy-crypto.js';
import type { PublicDevice } from './domain.js';
import type { AndroidDeviceRepository, DeviceTokenCrypto, NewDevice, StoredDevice } from './service.js';

export interface AndroidSqlConnection { execute(sql: string, values?: unknown[]): Promise<[unknown, unknown]>; beginTransaction(): Promise<void>; commit(): Promise<void>; rollback(): Promise<void>; release(): void }
export interface AndroidSqlPool { execute(sql: string, values?: unknown[]): Promise<[unknown, unknown]>; getConnection(): Promise<AndroidSqlConnection> }
interface DeviceRow extends RowDataPacket { id:number; user_id:number; device_id:string; platform:string; name:string; app_version:string; token_ciphertext:string; token_prefix:string; revoked_at:string|null; last_used_at:string|null; last_seen_at:string|null; created_at:string; push_provider:string|null; push_enabled:number|boolean; push_last_success_at:string|null; push_last_error:string }
const publicColumns = 'id,device_id,platform,name,app_version,token_prefix,last_used_at,last_seen_at,created_at,push_provider,push_enabled,push_last_success_at,push_last_error';
function publicDevice(row: DeviceRow): PublicDevice { return { id: row.id, device_id: row.device_id, platform: row.platform, name: row.name, app_version: row.app_version, token_prefix: row.token_prefix, last_used_at: row.last_used_at, last_seen_at: row.last_seen_at, created_at: row.created_at, push_provider: row.push_provider, push_enabled: Boolean(row.push_enabled), push_last_success_at: row.push_last_success_at, push_last_error: row.push_last_error }; }

export function createDeviceTokenCrypto(keyHex: string): DeviceTokenCrypto { return { randomToken: () => randomBytes(32).toString('hex'), hashToken: tokenHash, encryptToken: (value) => encryptLegacySecret(value, keyHex), decryptToken: (value) => decryptLegacySecret(value, keyHex) }; }
export class MysqlAndroidDeviceRepository implements AndroidDeviceRepository {
  constructor(private readonly pool: AndroidSqlPool, private readonly executor: AndroidSqlPool | AndroidSqlConnection = pool) {}
  async listActive(userId:number) { const [rows] = await this.executor.execute(`SELECT ${publicColumns} FROM app_devices WHERE user_id=? AND revoked_at IS NULL ORDER BY id DESC`, [userId]); return (rows as DeviceRow[]).map(publicDevice); }
  async findForUpdate(userId:number, deviceId:string) { const [rows] = await this.executor.execute('SELECT * FROM app_devices WHERE user_id=? AND device_id=? FOR UPDATE', [userId, deviceId]); const row=(rows as DeviceRow[])[0]; return row ? { id:row.id,userId:row.user_id,deviceId:row.device_id,platform:row.platform,name:row.name,appVersion:row.app_version,tokenCiphertext:row.token_ciphertext,tokenPrefix:row.token_prefix,revokedAt:row.revoked_at } satisfies StoredDevice : null; }
  async create(r:NewDevice) { const [result]=await this.executor.execute('INSERT INTO app_devices(user_id,device_id,platform,name,app_version,token_hash,token_ciphertext,token_prefix,last_seen_at) VALUES(?,?,?,?,?,?,?,?,NOW())',[r.userId,r.deviceId,r.platform,r.name,r.appVersion,r.tokenHash,r.tokenCiphertext,r.tokenPrefix]); return (result as ResultSetHeader).insertId; }
  async restore(id:number,userId:number,r:Omit<NewDevice,'userId'|'deviceId'>) { await this.executor.execute("UPDATE app_devices SET platform=?,name=?,app_version=?,token_hash=?,token_ciphertext=?,token_prefix=?,last_used_at=NULL,last_seen_at=NOW(),revoked_at=NULL,push_provider=NULL,push_token_hash=NULL,push_token_ciphertext=NULL,push_enabled=0,push_last_success_at=NULL,push_last_error='' WHERE id=? AND user_id=?",[r.platform,r.name,r.appVersion,r.tokenHash,r.tokenCiphertext,r.tokenPrefix,id,userId]); }
  async refresh(id:number,userId:number,r:Pick<NewDevice,'platform'|'name'|'appVersion'>) { await this.executor.execute('UPDATE app_devices SET platform=?,name=?,app_version=?,last_seen_at=NOW() WHERE id=? AND user_id=?',[r.platform,r.name,r.appVersion,id,userId]); }
  async findPublic(id:number,userId:number) { const [rows]=await this.executor.execute(`SELECT ${publicColumns} FROM app_devices WHERE id=? AND user_id=?`,[id,userId]); const row=(rows as DeviceRow[])[0]; return row ? publicDevice(row) : null; }
  async revoke(id:number,userId:number) { await this.executor.execute('UPDATE app_devices SET revoked_at=COALESCE(revoked_at,NOW()),push_enabled=0 WHERE id=? AND user_id=?',[id,userId]); }
  async unregisterPush(id:number,userId:number) { await this.executor.execute("UPDATE app_devices SET push_provider=NULL,push_token_hash=NULL,push_token_ciphertext=NULL,push_enabled=0,push_last_error='' WHERE id=? AND user_id=?",[id,userId]); }
  async transaction<T>(work:(tx:AndroidDeviceRepository)=>Promise<T>) { const connection=await this.pool.getConnection(); try { await connection.beginTransaction(); const result=await work(new MysqlAndroidDeviceRepository(this.pool,connection)); await connection.commit(); return result; } catch(error) { await connection.rollback().catch(()=>undefined); throw error; } finally { connection.release(); } }
}
