import {randomBytes} from 'node:crypto';
import type {ResultSetHeader,RowDataPacket} from 'mysql2/promise';
import {decryptLegacySecret,encryptLegacySecret,tokenHash} from '../../platform/legacy-crypto.js';
import type {ActiveShare,CreateShare,PublicShare,ShareTokenCrypto,SharingRepository} from './service.js';
export interface SharingSqlConnection{execute(sql:string,values?:unknown[]):Promise<[unknown,unknown]>;beginTransaction():Promise<void>;commit():Promise<void>;rollback():Promise<void>;release():void}
export interface SharingSqlPool{execute(sql:string,values?:unknown[]):Promise<[unknown,unknown]>;getConnection():Promise<SharingSqlConnection>}
export function createShareTokenCrypto(keyHex:string):ShareTokenCrypto{return {randomToken:()=>randomBytes(32).toString('hex'),hashToken:tokenHash,encryptToken:v=>encryptLegacySecret(v,keyHex),decryptToken:v=>decryptLegacySecret(v,keyHex)};}
export class MysqlSharingRepository implements SharingRepository{constructor(private readonly pool:SharingSqlPool,private readonly executor:SharingSqlPool|SharingSqlConnection=pool){}
 async findActive(userId:number,now:Date){const [rows]=await this.executor.execute("SELECT l.id,l.user_id,l.expires_at,l.token_ciphertext,COUNT(p.id) pending_count FROM share_links l LEFT JOIN share_link_parcels sp ON sp.share_id=l.id LEFT JOIN parcels p ON p.id=sp.parcel_id AND p.user_id=l.user_id AND p.status='pending' WHERE l.user_id=? AND l.revoked_at IS NULL AND l.expires_at>? GROUP BY l.id,l.user_id,l.expires_at,l.token_ciphertext ORDER BY l.id DESC LIMIT 1",[userId,now]);const r=(rows as RowDataPacket[])[0];return r?{id:Number(r.id),userId:Number(r.user_id),tokenCiphertext:r.token_ciphertext===null?null:String(r.token_ciphertext),expiresAt:new Date(r.expires_at as string|Date),pendingCount:Number(r.pending_count)} satisfies ActiveShare:null;}
 async listPendingParcelIds(userId:number){const [rows]=await this.executor.execute("SELECT id FROM parcels WHERE user_id=? AND status='pending' ORDER BY received_at DESC,id DESC",[userId]);return (rows as RowDataPacket[]).map(r=>Number(r.id));}
 async create(v:CreateShare){const connection=await this.pool.getConnection();try{await connection.beginTransaction();const [result]=await connection.execute('INSERT INTO share_links(user_id,token_hash,token_ciphertext,expires_at) VALUES(?,?,?,?)',[v.userId,v.tokenHash,v.tokenCiphertext,v.expiresAt]);const id=(result as ResultSetHeader).insertId;for(const parcelId of v.parcelIds)await connection.execute('INSERT INTO share_link_parcels(share_id,parcel_id) SELECT ?,id FROM parcels WHERE id=? AND user_id=? AND status=\'pending\'',[id,parcelId,v.userId]);await connection.commit();return id;}catch(error){await connection.rollback().catch(()=>undefined);throw error;}finally{connection.release();}}
 async revokeActive(userId:number,now:Date){await this.executor.execute('UPDATE share_links SET revoked_at=? WHERE user_id=? AND revoked_at IS NULL',[now,userId]);}
 async findPublic(hash:string,now:Date):Promise<PublicShare|null>{const [links]=await this.executor.execute('SELECT id,expires_at FROM share_links WHERE token_hash=? AND revoked_at IS NULL AND expires_at>? LIMIT 1',[hash,now]);const link=(links as RowDataPacket[])[0];if(!link)return null;const [items]=await this.executor.execute("SELECT p.id,p.pickup_code,p.courier_name,p.received_at,TIMESTAMPDIFF(HOUR,p.received_at,?) age_hours,s.id station_id,COALESCE(s.name,'未命名驿站') station_name,COALESCE(s.address,'') station_address FROM share_link_parcels sp JOIN share_links l ON l.id=sp.share_id JOIN parcels p ON p.id=sp.parcel_id AND p.user_id=l.user_id LEFT JOIN stations s ON s.id=p.station_id AND s.user_id=l.user_id WHERE sp.share_id=? AND p.status='pending' ORDER BY s.id,p.received_at,p.id",[now,link.id]);return {expiresAt:new Date(link.expires_at as string|Date),items:items as Array<RowDataPacket&{id:number}>};}
 async markPublicParcelPicked(hash:string,parcelId:number,now:Date){const [result]=await this.executor.execute("UPDATE parcels p JOIN share_link_parcels sp ON sp.parcel_id=p.id JOIN share_links l ON l.id=sp.share_id AND l.user_id=p.user_id SET p.status='picked_up',p.picked_up_at=? WHERE l.token_hash=? AND l.revoked_at IS NULL AND l.expires_at>? AND p.id=? AND p.status='pending'",[now,hash,now,parcelId]);return (result as ResultSetHeader).affectedRows===1;}}
