CREATE TABLE IF NOT EXISTS official_ai_config (
 id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
 display_name VARCHAR(80) NOT NULL,
 base_url VARCHAR(500) NOT NULL,
 api_key_ciphertext TEXT NOT NULL,
 api_key_hint VARCHAR(20) NOT NULL DEFAULT '',
 model_name VARCHAR(160) NOT NULL,
 is_enabled TINYINT(1) NOT NULL DEFAULT 0,
 last_test_status ENUM('untested','success','failed') NOT NULL DEFAULT 'untested',
 last_test_message VARCHAR(255) NOT NULL DEFAULT '',
 last_tested_at DATETIME NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS official_ai_user_selection (
 user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
 selected TINYINT(1) NOT NULL DEFAULT 1,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 CONSTRAINT fk_official_ai_selection_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
