import type { OpenAiClient } from './domain.js';
import { maskApiKey, normalizeOpenAiBaseUrl } from './domain.js';

export interface OfficialAiConfig { id:number;display_name:string;base_url:string;api_key_ciphertext:string;api_key_hint:string;model_name:string;is_enabled:number;last_test_status:string;last_test_message:string;last_tested_at:Date|string|null }
export interface OfficialAiPublic { id:number;display_name:string;model_name:string;is_enabled:number;available:number;selected:number }
export interface OfficialAiRepository {get():Promise<OfficialAiConfig|null>;save(input:{displayName:string;baseUrl:string;apiKeyCiphertext:string;apiKeyHint:string;modelName:string;isEnabled:boolean}):Promise<void>;updateTest(status:'success'|'failed',message:string):Promise<void>;getForUser(userId:number):Promise<OfficialAiPublic|null>;selectForUser(userId:number):Promise<void>}
type Result={status:number;body:{code:0|1;message?:string;data?:unknown}};
const fail=(message:string):Result=>({status:422,body:{code:1,message}});
const text=(value:unknown):string=>typeof value==='string'?value:'';
export class OfficialAiService{
 constructor(private readonly repository:OfficialAiRepository,private readonly deps:{encrypt(value:string):string;decrypt(value:string):string;validateUrl(url:string):Promise<boolean>;client:OpenAiClient}){}
 async adminStatus():Promise<Result>{const row=await this.repository.get();return {status:200,body:{code:0,data:row?{...row,api_key_ciphertext:undefined}:null}}}
 private async credentials(input:Record<string,unknown>):Promise<{base:string;key:string;model:string}|Result>{const old=await this.repository.get(),base=normalizeOpenAiBaseUrl(text(input.base_url)||old?.base_url||''),supplied=text(input.api_key).trim(),key=supplied||this.deps.decrypt(old?.api_key_ciphertext??''),model=(text(input.model_name)||old?.model_name||'').trim();if(!key||!await this.deps.validateUrl(base))return fail('请填写有效的API地址和Key');return {base,key,model}}
 async fetchModels(input:Record<string,unknown>):Promise<Result>{const c=await this.credentials(input);if('status'in c)return c;try{return {status:200,body:{code:0,message:'模型获取成功',data:{models:await this.deps.client.fetchModels(c.base,c.key)}}}}catch(error){return fail(`获取失败：${error instanceof Error?error.message:String(error)}`)}}
 async test(input:Record<string,unknown>):Promise<Result>{const c=await this.credentials(input);if('status'in c)return c;try{const models=await this.deps.client.fetchModels(c.base,c.key),model=c.model||models[0]||'';if(!model)throw new Error('没有可测试的模型');await this.deps.client.test(c.base,c.key,model);return {status:200,body:{code:0,message:'连接测试成功',data:{models}}}}catch(error){const message=error instanceof Error?error.message:String(error);return fail(`测试失败：${message}`)}}
 async save(input:Record<string,unknown>):Promise<Result>{const old=await this.repository.get(),displayName=text(input.display_name).trim(),baseUrl=normalizeOpenAiBaseUrl(text(input.base_url)),modelName=text(input.model_name).trim(),key=text(input.api_key).trim(),plainKey=key||this.deps.decrypt(old?.api_key_ciphertext??''),isEnabled=input.is_enabled===true||input.is_enabled===1||input.is_enabled==='1'||input.is_enabled==='true'||input.is_enabled==='on';if(!displayName||!modelName||!plainKey||!await this.deps.validateUrl(baseUrl))return fail('请完整填写名称、地址、Key和模型');if(isEnabled){try{await this.deps.client.test(baseUrl,plainKey,modelName)}catch(error){return fail(`启用前测试失败：${error instanceof Error?error.message:String(error)}`)}}await this.repository.save({displayName,baseUrl,apiKeyCiphertext:key?this.deps.encrypt(key):old!.api_key_ciphertext,apiKeyHint:key?maskApiKey(key):old!.api_key_hint,modelName,isEnabled});if(isEnabled)await this.repository.updateTest('success','连接正常');return {status:200,body:{code:0,message:'保存成功'}}}
 async publicStatus(userId:number):Promise<Result>{const row=await this.repository.getForUser(userId);return {status:200,body:{code:0,data:row??{available:0,selected:0,is_enabled:0,last_test_status:'untested'}}}}
 async selectForUser(userId:number):Promise<Result>{const row=await this.repository.getForUser(userId);if(!row||!row.available)return fail('官方模型暂不可用，请添加自己的模型');await this.repository.selectForUser(userId);return {status:200,body:{code:0,message:'已选择官方模型'}}}
}
