import type { OfficialAiConfig,OfficialAiPublic,OfficialAiRepository } from './official.js';
interface OfficialAiConnection extends OfficialAiSql{beginTransaction():Promise<void>;commit():Promise<void>;rollback():Promise<void>;release():void}
export interface OfficialAiSql{execute(sql:string,values?:unknown[]):Promise<[unknown,unknown]>;getConnection():Promise<OfficialAiConnection>}
export class MysqlOfficialAiRepository implements OfficialAiRepository{
 constructor(private readonly sql:OfficialAiSql){}
 async get():Promise<OfficialAiConfig|null>{const [rows]=await this.sql.execute('SELECT * FROM official_ai_config WHERE id=1');return (rows as OfficialAiConfig[])[0]??null}
 async save(input:{displayName:string;baseUrl:string;apiKeyCiphertext:string;apiKeyHint:string;modelName:string;isEnabled:boolean}):Promise<void>{await this.sql.execute("INSERT INTO official_ai_config(id,display_name,base_url,api_key_ciphertext,api_key_hint,model_name,is_enabled) VALUES(1,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE display_name=VALUES(display_name),base_url=VALUES(base_url),api_key_ciphertext=VALUES(api_key_ciphertext),api_key_hint=VALUES(api_key_hint),model_name=VALUES(model_name),is_enabled=VALUES(is_enabled)",[input.displayName,input.baseUrl,input.apiKeyCiphertext,input.apiKeyHint,input.modelName,input.isEnabled?1:0])}
 async updateTest(status:'success'|'failed',message:string):Promise<void>{await this.sql.execute('UPDATE official_ai_config SET last_test_status=?,last_test_message=?,last_tested_at=NOW() WHERE id=1',[status,message])}
 async getForUser(userId:number):Promise<OfficialAiPublic|null>{const [rows]=await this.sql.execute("SELECT c.id,c.display_name,c.model_name,c.is_enabled,IF(c.is_enabled=1 AND c.last_test_status='success',1,0) available,IF(s.selected=1,1,0) selected FROM official_ai_config c LEFT JOIN official_ai_user_selection s ON s.user_id=? WHERE c.id=1",[userId]);return (rows as OfficialAiPublic[])[0]??null}
 async selectForUser(userId:number):Promise<void>{const row=await this.getForUser(userId);if(!row?.available)throw new Error('官方模型暂不可用');const c=await this.sql.getConnection();try{await c.beginTransaction();await c.execute('UPDATE ai_providers SET is_active=0 WHERE user_id=?',[userId]);await c.execute('INSERT INTO official_ai_user_selection(user_id,selected) VALUES(?,1) ON DUPLICATE KEY UPDATE selected=1',[userId]);await c.commit()}catch(error){await c.rollback();throw error}finally{c.release()}}
}
