import type { ResultSetHeader, RowDataPacket } from 'mysql2/promise';
import { ActiveAiProviderDeleteError, AiProviderNotFoundError, type AiProviderRepository, type AiProviderRow, type AiStatus, type PublicAiProvider, type SaveAiProvider } from './domain.js';

export interface AiSqlExecutor { execute(this: void, sql: string, values?: unknown[]): Promise<[unknown, unknown]> }
export interface AiConnection extends AiSqlExecutor { beginTransaction(): Promise<void>; commit(): Promise<void>; rollback(): Promise<void>; release(): void }
export interface AiPool extends AiSqlExecutor { getConnection(): Promise<AiConnection> }
interface CountRow extends RowDataPacket { count: number | string }
interface ActiveRow extends RowDataPacket { is_active: number }

export class MysqlAiProviderRepository implements AiProviderRepository {
  constructor(private readonly pool: AiPool) {}
  async list(userId: number): Promise<PublicAiProvider[]> { const [rows] = await this.pool.execute('SELECT id,display_name,base_url,api_key_hint,model_name,is_active,last_test_status,last_test_message,last_tested_at,created_at FROM ai_providers WHERE user_id=? ORDER BY is_active DESC,id DESC', [userId]); return rows as PublicAiProvider[]; }
  async find(userId: number, id: number): Promise<AiProviderRow | null> { const [rows] = await this.pool.execute('SELECT * FROM ai_providers WHERE id=? AND user_id=?', [id, userId]); return (rows as AiProviderRow[])[0] ?? null; }
  async active(userId: number): Promise<AiProviderRow | null> { const [rows] = await this.pool.execute('SELECT * FROM ai_providers WHERE user_id=? AND is_active=1 ORDER BY id DESC LIMIT 1', [userId]); return (rows as AiProviderRow[])[0] ?? null; }
  async count(userId: number): Promise<number> { const [rows] = await this.pool.execute('SELECT COUNT(*) count FROM ai_providers WHERE user_id=?', [userId]); return Number((rows as CountRow[])[0]?.count ?? 0); }
  async save(userId: number, p: SaveAiProvider): Promise<void> { if (p.id > 0) { const [result] = await this.pool.execute('UPDATE ai_providers SET display_name=?,base_url=?,api_key_ciphertext=?,api_key_hint=?,model_name=? WHERE id=? AND user_id=?', [p.displayName, p.baseUrl, p.apiKeyCiphertext, p.apiKeyHint, p.modelName, p.id, userId]); if ((result as ResultSetHeader).affectedRows === 0 && await this.find(userId, p.id) === null) throw new AiProviderNotFoundError(); return; } await this.pool.execute('INSERT INTO ai_providers(user_id,display_name,base_url,api_key_ciphertext,api_key_hint,model_name,is_active) VALUES(?,?,?,?,?,?,?)', [userId, p.displayName, p.baseUrl, p.apiKeyCiphertext, p.apiKeyHint, p.modelName, p.isActive ? 1 : 0]); }
  async select(userId: number, id: number): Promise<void> { const connection = await this.pool.getConnection(); try { await connection.beginTransaction(); const [rows] = await connection.execute('SELECT id FROM ai_providers WHERE id=? AND user_id=? FOR UPDATE', [id, userId]); if ((rows as RowDataPacket[])[0] === undefined) throw new AiProviderNotFoundError(); await connection.execute('UPDATE ai_providers SET is_active=0 WHERE user_id=?', [userId]); await connection.execute('UPDATE ai_providers SET is_active=1 WHERE id=? AND user_id=?', [id, userId]); await connection.execute('UPDATE official_ai_user_selection SET selected=0 WHERE user_id=?',[userId]); await connection.commit(); } catch (e) { try { await connection.rollback(); } catch { /* preserve original transaction error */ } throw e; } finally { connection.release(); } }
  async delete(userId: number, id: number): Promise<void> { const [rows] = await this.pool.execute('SELECT is_active FROM ai_providers WHERE id=? AND user_id=?', [id, userId]); const row = (rows as ActiveRow[])[0]; if (row === undefined) throw new AiProviderNotFoundError(); if (row.is_active === 1) throw new ActiveAiProviderDeleteError(); await this.pool.execute('DELETE FROM ai_providers WHERE id=? AND user_id=?', [id, userId]); }
  async updateTest(userId: number, id: number, status: 'success' | 'failed', message: string): Promise<void> { await this.pool.execute('UPDATE ai_providers SET last_test_status=?,last_test_message=?,last_tested_at=NOW() WHERE id=? AND user_id=?', [status, message, id, userId]); }
  async status(userId: number): Promise<AiStatus> { const [counts] = await this.pool.execute("SELECT SUM(ai_status='pending') pending_count,SUM(ai_status='failed') failed_count,SUM(ai_status='no_config') no_config_count,SUM(ai_status='pending' AND ai_error='AI超时，等待重试') timeout_retry_count FROM incoming_messages WHERE user_id=? AND received_at>=DATE_SUB(NOW(),INTERVAL 7 DAY)", [userId]); const [providers] = await this.pool.execute("SELECT display_name,model_name FROM ai_providers WHERE user_id=? AND is_active=1 UNION ALL SELECT c.display_name,c.model_name FROM official_ai_config c JOIN official_ai_user_selection s ON s.user_id=? AND s.selected=1 WHERE c.id=1 AND c.is_enabled=1 AND c.last_test_status='success' LIMIT 1", [userId,userId]); return { counts: (counts as AiStatus['counts'][])[0] ?? { pending_count: null, failed_count: null, no_config_count: null }, provider: (providers as AiStatus['provider'][])[0] ?? null }; }
}
