import type { ResultSetHeader, RowDataPacket } from 'mysql2/promise';
/* eslint-disable no-irregular-whitespace */
import { normalizeNewStationAddress, normalizeNewStationName, resolveStationMatchId, type KnownStation, type PickupResult } from './domain.js';
import type { RecognitionMessage, RecognitionProvider, RecognitionRepository } from './service.js';
export interface RecognitionConnection { execute(sql: string, values?: unknown[]): Promise<[unknown, unknown]>; beginTransaction(): Promise<void>; commit(): Promise<void>; rollback(): Promise<void>; release(): void }
export interface RecognitionPool { execute(sql: string, values?: unknown[]): Promise<[unknown, unknown]>; getConnection(): Promise<RecognitionConnection> }
export class MysqlRecognitionRepository implements RecognitionRepository {
  constructor(private readonly pool: RecognitionPool) {}
  async activeProvider(userId: number): Promise<RecognitionProvider | null> { const [rows] = await this.pool.execute("SELECT id,base_url,api_key_ciphertext,model_name,'user' source FROM ai_providers WHERE user_id=? AND is_active=1 UNION ALL SELECT NULL id,c.base_url,c.api_key_ciphertext,c.model_name,'official' source FROM official_ai_config c JOIN official_ai_user_selection s ON s.user_id=? AND s.selected=1 WHERE c.id=1 AND c.is_enabled=1 AND c.last_test_status='success' LIMIT 1", [userId,userId]); return (rows as RecognitionProvider[])[0] ?? null; }
  async message(userId: number, id: number): Promise<RecognitionMessage | null> { const [rows] = await this.pool.execute('SELECT id,user_id,raw_message,received_at,ai_status FROM incoming_messages WHERE id=? AND user_id=?', [id, userId]); return (rows as RecognitionMessage[])[0] ?? null; }
  async stations(userId: number, limit: number): Promise<KnownStation[]> { const safe = Math.max(1, Math.min(50, limit)); const [rows] = await this.pool.execute(`SELECT s.id,s.name,s.address,COALESCE(NULLIF(s.courier_names,''),COALESCE(GROUP_CONCAT(DISTINCT NULLIF(p.courier_name,'') ORDER BY p.courier_name SEPARATOR ','),'')) courier_names FROM stations s LEFT JOIN parcels p ON p.station_id=s.id AND p.user_id=s.user_id WHERE s.user_id=? GROUP BY s.id,s.name,s.address,s.courier_names,s.is_manual,s.use_count,s.last_used_at,s.created_at ORDER BY s.is_manual DESC,COALESCE(s.last_used_at,s.created_at) DESC LIMIT ${safe}`, [userId]); return rows as KnownStation[]; }
  async persist(messageId: number, userId: number, provider: { id: number | null; model_name: string }, result: PickupResult, metadata: { recognitionSource: 'ai' | 'local'; fallbackReason: string }): Promise<Record<string, unknown>> {
    if (!result.is_pickup_message) { await this.pool.execute("UPDATE incoming_messages SET ai_status='not_pickup',parse_status='ignored',ai_provider_id=?,ai_model=?,ai_result_json=?,ai_error=?,ai_processed_at=NOW(),ai_attempts=ai_attempts+1 WHERE id=? AND user_id=?", [provider.id, provider.model_name, JSON.stringify(result), metadata.fallbackReason.slice(0, 500), messageId, userId]); return { status: 'not_pickup', codes: [] }; }
    const connection = await this.pool.getConnection();
    try {
      await connection.beginTransaction();
      await connection.execute('SELECT id FROM users WHERE id=? FOR UPDATE',[userId]);
      let stationId = result.matched_station_id;
      if (stationId !== null) { const [rows] = await connection.execute('SELECT id FROM stations WHERE id=? AND user_id=?', [stationId, userId]); if ((rows as RowDataPacket[])[0] === undefined) stationId = null; }
      if (stationId === null) {
        const name = normalizeNewStationName(result.station_name) || normalizeNewStationAddress(result.station_address) || '未识别驿站'; const address = normalizeNewStationAddress(result.station_address);
        await connection.execute('SELECT id FROM stations WHERE user_id=? FOR UPDATE', [userId]);
        const [knownRows] = await connection.execute('SELECT id,name,address,courier_names FROM stations WHERE user_id=? ORDER BY id', [userId]);
        stationId = resolveStationMatchId({ ...result, station_name: name, station_address: address }, `【${name}】\n地址：${address}\n取件码：${result.pickup_codes[0] ?? ''}`, knownRows as KnownStation[]);
        if (stationId === null) { await connection.execute("INSERT INTO stations(user_id,name,normalized_name,address,use_count,last_used_at) VALUES(?,?,?,?,0,NULL) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),name=VALUES(name),address=IF(VALUES(address)<>'',VALUES(address),address)", [userId, name, name.replace(/[\s　]+/gu, '').toLowerCase(), address]); const [idRows] = await connection.execute('SELECT LAST_INSERT_ID() id'); stationId = Number((idRows as { id: number }[])[0]?.id ?? 0); }
      }
      const uniqueCodes=[...new Set(result.pickup_codes)];
      let existingCodes=new Set<string>();
      if(uniqueCodes.length){const placeholders=uniqueCodes.map(()=>'?').join(',');const [existingRows]=await connection.execute(`SELECT pickup_code FROM parcels WHERE user_id=? AND BINARY pickup_code IN (${placeholders}) FOR UPDATE`,[userId,...uniqueCodes]);existingCodes=new Set((existingRows as {pickup_code:string}[]).map(row=>row.pickup_code));}
      const insertedCodes:string[]=[];const duplicateCodes:string[]=[];
      for (const code of uniqueCodes) { if(existingCodes.has(code)){duplicateCodes.push(code);continue} const [insert] = await connection.execute("INSERT INTO parcels(user_id,message_id,station_id,pickup_code,courier_name,pickup_time_text,status,needs_review,received_at) SELECT user_id,id,?,?,?,?, 'pending',0,received_at FROM incoming_messages WHERE id=? AND user_id=?", [stationId, code, result.courier_name, result.pickup_time, messageId, userId]); if((insert as ResultSetHeader).affectedRows===1)insertedCodes.push(code);else duplicateCodes.push(code); }
      await connection.execute('UPDATE stations SET use_count=use_count+?,last_used_at=(SELECT received_at FROM incoming_messages WHERE id=?) WHERE id=? AND user_id=?', [insertedCodes.length, messageId, stationId, userId]);
      await connection.execute("UPDATE incoming_messages SET ai_status='success',parse_status='parsed',ai_provider_id=?,ai_model=?,ai_result_json=?,parse_result_json=?,ai_error=?,ai_processed_at=NOW(),ai_attempts=ai_attempts+1 WHERE id=? AND user_id=?", [provider.id, provider.model_name, JSON.stringify(result), JSON.stringify(result), metadata.fallbackReason.slice(0, 500), messageId, userId]);
      await connection.commit();
      return { status: insertedCodes.length?'created':'duplicate', codes: insertedCodes, duplicate_codes: duplicateCodes, station_id: stationId };
    } catch (e) { try { await connection.rollback(); } catch { /* preserve original transaction error */ } throw e; } finally { connection.release(); }
  }
  async markFailure(messageId: number, userId: number, provider: RecognitionProvider | null, error: string, result?: unknown): Promise<void> { await this.pool.execute("UPDATE incoming_messages SET ai_status=?,parse_status='needs_review',ai_provider_id=?,ai_model=?,ai_result_json=?,ai_error=?,ai_processed_at=NOW(),ai_attempts=ai_attempts+1 WHERE id=? AND user_id=?", [provider ? 'failed' : 'no_config', provider?.id ?? null, provider?.model_name ?? 'local-rule-v1', JSON.stringify(result ?? null), error.slice(0, 500), messageId, userId]); }

  async updateImageSource(messageId:number,userId:number,rawMessage:string,result:unknown):Promise<void>{await this.pool.execute('UPDATE incoming_messages SET raw_message=?,ai_result_json=? WHERE id=? AND user_id=?',[rawMessage,JSON.stringify(result),messageId,userId]);}
  async createImageMessage(userId: number, input: { rawMessage: string; fingerprint: string; provider: RecognitionProvider; result: PickupResult; clientIp: string }): Promise<{ id: number; duplicate: boolean }> { const [rows] = await this.pool.execute('SELECT id,ai_status FROM incoming_messages WHERE user_id=? AND request_fingerprint=?', [userId, input.fingerprint]); const existing = (rows as { id: number; ai_status:string }[])[0]; if (existing) { if(existing.ai_status==='pending'){const [claim]=await this.pool.execute("UPDATE incoming_messages SET ai_attempts=ai_attempts+1,ai_processed_at=NOW() WHERE id=? AND user_id=? AND ai_status='pending' AND ai_attempts=0 AND created_at<=DATE_SUB(NOW(),INTERVAL 2 MINUTE)",[existing.id,userId]);if((claim as ResultSetHeader).affectedRows===1)return {id:existing.id,duplicate:false};} return { id: existing.id, duplicate: true }; } const [insert] = await this.pool.execute("INSERT INTO incoming_messages(user_id,sender,raw_sender,raw_message,received_at,request_fingerprint,parse_status,ai_status,ai_provider_id,ai_model,ai_result_json,client_ip) VALUES(?,'图片识别','图片识别',?,NOW(),?,'needs_review','pending',?,?,?,?)", [userId, input.rawMessage, input.fingerprint, input.provider.id, input.provider.model_name, JSON.stringify(input.result), input.clientIp]); return { id: (insert as ResultSetHeader).insertId, duplicate: false }; }
  async saveImageFailure(userId: number, input: { fingerprint: string; rawMessage: string; provider: RecognitionProvider; result: unknown; error: string; clientIp: string }): Promise<number> { const [insert] = await this.pool.execute("INSERT INTO incoming_messages(user_id,sender,raw_sender,raw_message,received_at,request_fingerprint,parse_status,ai_status,ai_provider_id,ai_model,ai_result_json,ai_error,ai_processed_at,client_ip) VALUES(?,'图片识别','图片识别',?,NOW(),?,'needs_review','failed',?,?,?,?,NOW(),?) ON DUPLICATE KEY UPDATE ai_status='failed',ai_error=VALUES(ai_error),ai_processed_at=NOW(),ai_attempts=ai_attempts+1,id=LAST_INSERT_ID(id)", [userId, input.rawMessage, input.fingerprint, input.provider.id, input.provider.model_name, JSON.stringify(input.result), input.error.slice(0, 500), input.clientIp]); return (insert as ResultSetHeader).insertId; }
}
