import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import type { RecognitionService, UploadedImage } from './service.js';
import type { ImageRecognitionQueueService } from './queue.js';
export interface RecognitionRouteOptions { service: RecognitionService; queue?: ImageRecognitionQueueService; resolveUserId(request: FastifyRequest): Promise<number | null>; verifyCsrf(request: FastifyRequest): Promise<boolean>; parseImages?(request: FastifyRequest): Promise<UploadedImage[]> }
const failure = (message: string) => ({ code: 1 as const, message });
export function registerRecognitionRoutes(app: FastifyInstance, options: RecognitionRouteOptions): void {
  app.post('/api/retry-ai', async (request, reply) => { reply.header('Cache-Control', 'no-store'); const userId = await options.resolveUserId(request); if (userId === null) return reply.status(401).send(failure('请先登录')); if (!await options.verifyCsrf(request)) return reply.status(403).send(failure('CSRF校验失败')); const body = request.body !== null && typeof request.body === 'object' ? request.body as Record<string, unknown> : {}; const messageId=Number(body.message_id ?? 0); const queued=options.queue ? await options.queue.retry(userId,messageId) : null; const result=queued === null || queued.status === 404 ? await options.service.retry(userId,messageId) : queued; return reply.status(result.status).send(result.body); });
  app.post('/api/image-recognize', async (request, reply) => { reply.header('Cache-Control', 'no-store'); const userId = await options.resolveUserId(request); if (userId === null) return reply.status(401).send(failure('请先登录')); if (!await options.verifyCsrf(request)) return reply.status(403).send(failure('CSRF校验失败')); let images: UploadedImage[]; try { const body = request.body as { images?: UploadedImage[] } | undefined; images = options.parseImages === undefined ? (Array.isArray(body?.images) ? body.images : []) : await options.parseImages(request); } catch { return reply.status(400).send(failure('图片上传格式错误')); } const result = options.queue ? await options.queue.enqueue(userId, images, request.ip) : await options.service.recognizeImages(userId, images, request.ip); return reply.status(result.status).send(result.body); });
  const deleteFailed = async(request:FastifyRequest,reply:FastifyReply)=>{reply.header('Cache-Control','no-store');const userId=await options.resolveUserId(request);if(userId===null)return reply.status(401).send(failure('请先登录'));if(!await options.verifyCsrf(request))return reply.status(403).send(failure('CSRF校验失败'));if(!options.queue)return reply.status(404).send(failure('接口未启用'));const body=request.body!==null&&typeof request.body==='object'?request.body as Record<string,unknown>:{};if(request.url.endsWith('/recognition-records')&&body.action!=='delete')return reply.status(422).send(failure('不支持的操作'));const result=await options.queue.deleteFailed(userId,Number(body.message_id??0));return reply.status(result.status).send(result.body);};
  app.post('/api/recognition-records',deleteFailed);
  app.post('/api/recognition-records/failed',deleteFailed);
}
