import type {RowDataPacket} from 'mysql2/promise';
import type {NotificationPreferences,NotificationRepository,StoredSubscription} from './service.js';
export interface NotificationsSqlPool{execute(sql:string,values?:unknown[]):Promise<[unknown,unknown]>}
export class MysqlNotificationRepository implements NotificationRepository{constructor(private readonly pool:NotificationsSqlPool){}
 async getPreferences(userId:number){await this.pool.execute('INSERT IGNORE INTO notification_preferences(user_id) VALUES(?)',[userId]);const [rows]=await this.pool.execute("SELECT new_pending_enabled,daily_enabled,TIME_FORMAT(daily_time,'%H:%i') daily_time,timezone FROM notification_preferences WHERE user_id=?",[userId]);const row=((rows as RowDataPacket[])[0]??{}) as RowDataPacket;return {new_pending_enabled:Boolean(row.new_pending_enabled),daily_enabled:Boolean(row.daily_enabled),daily_time:String(row.daily_time??'20:00'),timezone:String(row.timezone??'Asia/Shanghai')};}
 async listDevices(userId:number){const [rows]=await this.pool.execute('SELECT endpoint_hash,last_success_at,created_at FROM push_subscriptions WHERE user_id=? ORDER BY id DESC',[userId]);return rows as unknown[];}
 async upsertSubscription(v:{userId:number;endpoint:string;endpointHash:string;p256dh:string;auth:string;userAgent:string}){await this.pool.execute("INSERT INTO push_subscriptions(user_id,endpoint,endpoint_hash,p256dh,auth,content_encoding,user_agent) VALUES(?,?,?,?,?,'aes128gcm',?) ON DUPLICATE KEY UPDATE user_id=VALUES(user_id),endpoint=VALUES(endpoint),p256dh=VALUES(p256dh),auth=VALUES(auth),user_agent=VALUES(user_agent),last_error=''",[v.userId,v.endpoint,v.endpointHash,v.p256dh,v.auth,v.userAgent]);}
 async deleteSubscription(userId:number,endpointHash:string){await this.pool.execute('DELETE FROM push_subscriptions WHERE user_id=? AND endpoint_hash=?',[userId,endpointHash]);}
 async savePreferences(userId:number,v:NotificationPreferences){await this.pool.execute('INSERT INTO notification_preferences(user_id,new_pending_enabled,daily_enabled,daily_time,timezone) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE last_daily_sent_date=IF(daily_enabled<>VALUES(daily_enabled) OR daily_time<>VALUES(daily_time) OR timezone<>VALUES(timezone),NULL,last_daily_sent_date),new_pending_enabled=VALUES(new_pending_enabled),daily_enabled=VALUES(daily_enabled),daily_time=VALUES(daily_time),timezone=VALUES(timezone)',[userId,v.new_pending_enabled,v.daily_enabled,`${v.daily_time}:00`,v.timezone]);}
 async listSubscriptions(userId:number){const [rows]=await this.pool.execute('SELECT id,endpoint,p256dh,auth,content_encoding FROM push_subscriptions WHERE user_id=?',[userId]);return (rows as RowDataPacket[]).map(r=>({id:Number(r.id),endpoint:String(r.endpoint),p256dh:String(r.p256dh),auth:String(r.auth),contentEncoding:String(r.content_encoding??'aes128gcm')} satisfies StoredSubscription));}
 async listAllSubscriptions(){const [rows]=await this.pool.execute('SELECT id,endpoint,p256dh,auth,content_encoding FROM push_subscriptions ORDER BY id');return (rows as RowDataPacket[]).map(r=>({id:Number(r.id),endpoint:String(r.endpoint),p256dh:String(r.p256dh),auth:String(r.auth),contentEncoding:String(r.content_encoding??'aes128gcm')} satisfies StoredSubscription));}
 async recordSuccess(id:number){await this.pool.execute("UPDATE push_subscriptions SET last_success_at=NOW(),last_error='' WHERE id=?",[id]);}async recordFailure(id:number,reason:string){await this.pool.execute('UPDATE push_subscriptions SET last_error=? WHERE id=?',[reason,id]);}async deleteExpired(id:number){await this.pool.execute('DELETE FROM push_subscriptions WHERE id=?',[id]);}}
