import {createHash} from 'node:crypto';
export interface SubscriptionInput {endpoint:string;keys:{p256dh:string;auth:string}}
export interface StoredSubscription {id:number;endpoint:string;p256dh:string;auth:string;contentEncoding:string}
export interface DeliveryResult {sent:number;failed:number}
export interface NotificationRepository {getPreferences(userId:number):Promise<Record<string,unknown>>;listDevices(userId:number):Promise<unknown[]>;upsertSubscription(value:{userId:number;endpoint:string;endpointHash:string;p256dh:string;auth:string;userAgent:string}):Promise<void>;deleteSubscription(userId:number,endpointHash:string):Promise<void>;savePreferences(userId:number,value:NotificationPreferences):Promise<void>;listSubscriptions(userId:number):Promise<StoredSubscription[]>;listAllSubscriptions():Promise<StoredSubscription[]>;recordSuccess(id:number):Promise<void>;recordFailure(id:number,reason:string):Promise<void>;deleteExpired(id:number):Promise<void>}
export interface PushSender {send(subscription:StoredSubscription,payload:Record<string,unknown>):Promise<{success:boolean;expired?:boolean;reason?:string}>}
export interface NotificationPreferences {new_pending_enabled:boolean;daily_enabled:boolean;daily_time:string;timezone:'Asia/Shanghai'}
export class NotificationValidationError extends Error {}
const hash=(v:string)=>createHash('sha256').update(v).digest('hex');
export class NotificationService {
 constructor(private readonly repository:NotificationRepository,private readonly sender:PushSender,private readonly vapidPublicKey:string){}
 async get(userId:number){const [preferences,devices]=await Promise.all([this.repository.getPreferences(userId),this.repository.listDevices(userId)]);return {vapid_public_key:this.vapidPublicKey,preferences,device_count:devices.length,devices};}
 async subscribe(userId:number,input:SubscriptionInput,userAgent:string){let url:URL;try{url=new URL(input.endpoint);}catch{throw new NotificationValidationError('设备订阅信息无效');}if(url.protocol!=='https:'||!input.keys.p256dh.trim()||!input.keys.auth.trim())throw new NotificationValidationError('设备订阅信息无效');await this.repository.upsertSubscription({userId,endpoint:input.endpoint,endpointHash:hash(input.endpoint),p256dh:input.keys.p256dh,auth:input.keys.auth,userAgent:userAgent.slice(0,500)});}
 async unsubscribe(userId:number,endpoint:string){if(endpoint.trim())await this.repository.deleteSubscription(userId,hash(endpoint.trim()));}
 async savePreferences(userId:number,input:Omit<NotificationPreferences,'timezone'>){if(!/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(input.daily_time))throw new NotificationValidationError('提醒时间格式错误');const value={...input,timezone:'Asia/Shanghai' as const};await this.repository.savePreferences(userId,value);return value;}
 async testPush(userId:number){return this.send(userId,{title:'取件助手服务器测试',body:'服务器后台推送已送达，划掉App后仍可接收提醒。',tag:`server-test-${Date.now()}`,url:'/'});}
 async broadcast(input:{title:string;body:string;url:string}){return this.deliver(await this.repository.listAllSubscriptions(),{...input,tag:`admin-broadcast-${Date.now()}`});}
 async send(userId:number,payload:Record<string,unknown>):Promise<DeliveryResult>{const subscriptions=await this.repository.listSubscriptions(userId);let sent=0,failed=0;for(const subscription of subscriptions){try{const result=await this.sender.send(subscription,payload);if(result.success){sent++;await this.repository.recordSuccess(subscription.id);}else{failed++;if(result.expired)await this.repository.deleteExpired(subscription.id);else await this.repository.recordFailure(subscription.id,(result.reason??'发送失败').slice(0,255));}}catch(error){failed++;await this.repository.recordFailure(subscription.id,error instanceof Error?error.message.slice(0,255):'发送失败');}}return {sent,failed};}
 private async deliver(subscriptions:StoredSubscription[],payload:Record<string,unknown>):Promise<DeliveryResult>{let sent=0,failed=0;for(const subscription of subscriptions){try{const result=await this.sender.send(subscription,payload);if(result.success){sent++;await this.repository.recordSuccess(subscription.id);}else{failed++;if(result.expired)await this.repository.deleteExpired(subscription.id);else await this.repository.recordFailure(subscription.id,(result.reason??'发送失败').slice(0,255));}}catch(error){failed++;await this.repository.recordFailure(subscription.id,error instanceof Error?error.message.slice(0,255):'发送失败');}}return {sent,failed};}
}
